apiVersion: apps/v1
kind: Deployment
metadata:
  name: audioseek-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audioseek-frontend
  template:
    metadata:
      labels:
        app: audioseek-frontend
    spec:
      containers:
      - name: frontend
        image: us-east1-docker.pkg.dev/ie7374-475102/audioseek-repo/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        env:
        - name: API_URL
          value: "http://audioseek-api"
        - name: PROJECT_ID
          value: "ie7374-475102"
        - name: PROJECT_NUMBER
          value: "671506471835"
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: audioseek-secrets
              key: GEMINI_API_KEY
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: audioseek-secrets
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: audioseek-secrets
              key: GOOGLE_CLIENT_SECRET
        - name: GOOGLE_REDIRECT_URI
          value: "http://34.26.205.118.nip.io"  # Update this after deployment
---
apiVersion: v1
kind: Service
metadata:
  name: audioseek-frontend
spec:
  selector:
    app: audioseek-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
  type: LoadBalancer