name: Deploy Backend to GKE

on:
  push:
    branches:
      - main
    paths:
      - 'Data-Pipeline/**'
      - 'k8s/api.yaml'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/671506471835/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'audioseekgitconnect@ie7374-475102.iam.gserviceaccount.com'
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: audioseek-cluster
          location: us-east1
      
      - name: Configure Docker
        run: gcloud auth configure-docker us-east1-docker.pkg.dev
      
      - name: Build API image
        run: |
          docker build --platform linux/amd64 \
            -t us-east1-docker.pkg.dev/ie7374-475102/audioseek-repo/api:${{ github.sha }} \
            -t us-east1-docker.pkg.dev/ie7374-475102/audioseek-repo/api:latest \
            -f Data-Pipeline/Dockerfile Data-Pipeline
      
      - name: Push API image
        run: |
          docker push us-east1-docker.pkg.dev/ie7374-475102/audioseek-repo/api:${{ github.sha }}
          docker push us-east1-docker.pkg.dev/ie7374-475102/audioseek-repo/api:latest
      
      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/api.yaml -f k8s/mlflow.yaml
          kubectl set image deployment/audioseek-api api=us-east1-docker.pkg.dev/ie7374-475102/audioseek-repo/api:${{ github.sha }} --namespace=default
          kubectl rollout status deployment/audioseek-api --namespace=default --timeout=15m
